version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    networks:
      - farmers-network

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    networks:
      - farmers-network

networks:
  farmers-network:
    driver: bridge

